name: Haskell CI with Cabal

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

permissions: {}

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: List everything
        run: tree -alps .
      - name: PR merged event
        run: echo "${{ github.event.pull_request.merged }}"
      - name: PR review event
        run: echo "${{ github.event.review.state }}"
      - name: PR push event (.ref)
        run: echo "${{ github.event.push.ref }}"
      - name: PR push event
        run: echo "${{ github.event.push }}"
      - name: PR full event
        run: |
          cat << EOL
          ${{ toJson(github.event) }}
          EOL
