name: Cabal new project

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

permissions: {}

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - run: tree -alps .
      - run: cabal init --help
      # -m = --minimal
      # -n = --non-interactive
      - run: cabal init -n -m --no-comments
      - run: cabal configure --enable-tests --enable-benchmarks
      - run: tree -alps .
      - run: cat CHANGELOG.md
      - run: cat app/Main.hs
      - run: cat io-manager.cabal
      - run: cat ~/.cabal/config
      - run: cat cabal.project.local
