name: Postsubmit

on:
  workflow_run:
    workflows: [Postsubmit]
    types: [completed]
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - name: List everything
        run: |
          tree -alps .
          sleep 600
          tree -alps .
