name: Haskell Cabal

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

permissions: {}

jobs:
  test:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ghc: ["8.10.7", "9.2.5", "9.4.4"]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          persist-credentials: false

      - name: Setup Haskell Compiler (cabal)
        id: setup-haskell
        uses: haskell/actions/setup@5ff2575cfa27ef8693b7252e0ed1cb0ad87af57e # v2.3.7
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Cache dist-newstyle
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: dist-newstyle
          key: dist-newstyle-${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('simple-echo-example/*') }}
          restore-keys: |
            dist-newstyle-${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-
            dist-newstyle-${{ matrix.os }}-${{ matrix.ghc }}-

      - name: Cache ~/.cabal/store
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-store-${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: cabal-store-${{ matrix.os }}-${{ matrix.ghc }}-

      - name: Configure to run tests and benchmarks
        run: cabal configure --enable-tests --enable-benchmarks

      - name: Build code
        run: cabal build

      - name: Test code
        run: cabal test || true  # TODO(mihaimaruseac): Fix this

      - name: Benchmark code
        run: cabal bench || true  # TODO(mihaimaruseac): Fix this

      - name: Generate documentation
        run: cabal haddock all
