name: Haskell Cabal

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

permissions: {}

jobs:
  test:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't cancel other jobs if one fails
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ghc: [8.10.7, 9.0.2, 9.2.8, 9.4.7, 9.6.3]
    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          persist-credentials: false

      - name: Setup Haskell Compiler (cabal)
        id: setup-haskell
        uses: haskell-actions/setup@9933312ae77442f1fc8a613c182206d0e45ea0e8 # v2.5.0
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Cache dist-newstyle
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: dist-newstyle
          key: dist-newstyle-${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('simple-echo-example/*') }}
          restore-keys: |
            dist-newstyle-${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}-
            dist-newstyle-${{ matrix.os }}-${{ matrix.ghc }}-

      - name: Cache ~/.cabal/store
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-store-${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal') }}
          restore-keys: cabal-store-${{ matrix.os }}-${{ matrix.ghc }}-

      - name: Configure to run tests and benchmarks
        run: cabal configure --enable-tests --enable-benchmarks

      - name: Build code
        run: cabal build

      - name: Test code
        run: cabal test || true  # TODO(mihaimaruseac): Fix this

      - name: Benchmark code
        run: cabal bench || true  # TODO(mihaimaruseac): Fix this

      - name: Generate documentation
        run: cabal haddock all
